# THIS FILE HAS BEEN AUTOGENERATED. To update:
# 1. modify the `_deps` dict in setup.py
# 2. run `make deps_table_update`
deps = {
    "triton": "triton>=2.2.0",
    "paddlepaddle-gpu": "paddlepaddle-gpu>=3.0.0",
    "paddlenlp": "paddlenlp>=3.0.0",
    "einops": "einops>=0.6.1",
    "isort": "isort>=5.5.4",
    "numpy": "numpy",
    "parameterized": "parameterized",
    "protobuf": "protobuf>=3.20.3,<4",
    "pytest": "pytest",
    "pytest-timeout": "pytest-timeout",
    "pytest-xdist": "pytest-xdist",
    "python": "python>=3.8.0",
    "black": "black",
    "hf-doc-builder": "hf-doc-builder>=0.3.0",
    "urllib3": "urllib3<=2.0.0",
    "ruff": "ruff==0.1.5",
    "GitPython": "GitPython<3.1.19",
}
